use_frameworks!

platform :ios, '8.0'

target 'HomeModule_Category_Example' do
  pod 'HomeModule_Category', :path => '../'

  target 'HomeModule_Category_Tests' do
    inherit! :search_paths

    pod "CTMediator" 
  end
end
